language: objective-c

branches:
  only:
    - master

xcode_project: TransitApp/TransitApp.xcodeproj
xcode_scheme: TransitApp/TransitAppTests
osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1

script:
  - xcodebuild test -project TransitApp/TransitApp.xcodeproj -scheme TransitAppTests
